export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const START_GAME = 'GAME/START_GAME';
export const RESTART_GAME = 'GAME/RESTART_GAME';
export const FINISH_GAME = 'GAME/FINISH_GAME';
export const TOGGLE_FULLSCREEN = 'GAME/TOGGLE_FULLSCREEN';
export const UPDATE_GAME_FIELD = 'GAME/UPDATE_GAME_FIEL';
export const SET_GAME_SIZE = 'GAME/SET_GAME_SIZE';
export const GAME_FAILED = 'GAME/GAME_FAILED';
export const GAME_WON = 'GAME/GAME_WON';
export const UPDATE_SCORE = 'GAME/UPDATE_SCORE'

export const SELECT_LANGUAGE = 'SETTINGS/SELECT_LANGUAGE';
export const SELECT_THEME = 'SETTINGS/SELECT_THEME';
export const TOGGLE_BTNS_VISABILITY = 'SETTINGS/TOGGLE_BTNS_VISABILITY';

export const SET_SOUNDS_VOLUME = 'SOUNDS/SET_SOUNDS_VOLUME';
export const SET_MUSIC_VOLUME = 'SOUNDS/SET_MUSIC_VOLUME';
export const PlAY_CELL_SOUND= 'SOUNDS/PlAY_CELL_SOUND';