export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';

export const START_GAME = 'GAME/START_GAME';
export const FINISH_GAME = 'GAME/FINISH_GAME';
export const TOGGLE_FULLSCREEN = 'GAME/TOGGLE_FULLSCREEN';

